// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZgGNF-VHgukBSmOjdQsynl8SsNgEflPo',
    appId: '1:524062546417:web:f0b4f06f6a418e78178c50',
    messagingSenderId: '524062546417',
    projectId: 'registronotas2025-b55ad',
    authDomain: 'registronotas2025-b55ad.firebaseapp.com',
    storageBucket: 'registronotas2025-b55ad.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD04x04OfobLauOo54dbfGJHdHKk_Hr3mk',
    appId: '1:524062546417:android:5b00a93b3e41dc1b178c50',
    messagingSenderId: '524062546417',
    projectId: 'registronotas2025-b55ad',
    storageBucket: 'registronotas2025-b55ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQGBX5Ro6pHXnYPgah2UAWPf0r_iaEbXI',
    appId: '1:524062546417:ios:3de5a6e67e7fb4f7178c50',
    messagingSenderId: '524062546417',
    projectId: 'registronotas2025-b55ad',
    storageBucket: 'registronotas2025-b55ad.firebasestorage.app',
    iosBundleId: 'com.example.taller1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQGBX5Ro6pHXnYPgah2UAWPf0r_iaEbXI',
    appId: '1:524062546417:ios:3de5a6e67e7fb4f7178c50',
    messagingSenderId: '524062546417',
    projectId: 'registronotas2025-b55ad',
    storageBucket: 'registronotas2025-b55ad.firebasestorage.app',
    iosBundleId: 'com.example.taller1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZgGNF-VHgukBSmOjdQsynl8SsNgEflPo',
    appId: '1:524062546417:web:68e86ef2882871c0178c50',
    messagingSenderId: '524062546417',
    projectId: 'registronotas2025-b55ad',
    authDomain: 'registronotas2025-b55ad.firebaseapp.com',
    storageBucket: 'registronotas2025-b55ad.firebasestorage.app',
  );

}